// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwnI7odtevvBrneGCw7jhw0WzNlmeCKQ',
    appId: '1:498124971501:web:cbd29f6f5efd7ddd415be4',
    messagingSenderId: '498124971501',
    projectId: 'vihan-traffic-management',
    authDomain: 'vihan-traffic-management.firebaseapp.com',
    storageBucket: 'vihan-traffic-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMIovaBap68XjjgauKFLw0wIXvITvEWk',
    appId: '1:498124971501:android:dea2f8344f0f80c9415be4',
    messagingSenderId: '498124971501',
    projectId: 'vihan-traffic-management',
    storageBucket: 'vihan-traffic-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGB33uS63MpjtqS_qLENPosEwdIqMhdg',
    appId: '1:498124971501:ios:a2a388010cb6fd8e415be4',
    messagingSenderId: '498124971501',
    projectId: 'vihan-traffic-management',
    storageBucket: 'vihan-traffic-management.firebasestorage.app',
    iosBundleId: 'com.example.vihan',
  );
}
